[build]
  # Comando para build (para frontend estático)
  command = "echo 'Frontend build complete'"
  # Diretório que será publicado
  publish = "public"

[build.environment]
  # Versão do Node.js
  NODE_VERSION = "18"

# Configurações para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

# Configurações para arquivos estáticos
[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
